### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by duyvuleo** [acmi-lab/modular-summarization#3]
Hi,

Thanks for the interesting work.

Is there any chance that training scripts can be released to replicate the results presented in the paper, especially for AMI datasets?

thanks!

**Comment by kukrishna** [comment]
Hi,

There is a colab notebook here that shows how to run the models for the AMI datasets

https://colab.research.google.com/drive/1P0dp4rctvhSWdzfgml4B7yt3Qketrzst?usp=sharing

**Comment by kukrishna** [comment]
Hi

The training was done using allennlp (v0.8.5) which provides a simple way to train a model using config file. If you extract the models that we have released, you can see a config.json file inside which has the hyperparameters used for training. You can use them with the allennlp train command to train the model. 

You can look into the documentation of allennlp to see how to train a model using config file.

Thanks
